Use customer_beheviour;
Select * from customer_beheviour;
#Q1. What is the total revenue generated by male vs. female customers?

SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer_beheviour
GROUP BY gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT 
    customer_id, purchase_amount
FROM
    customer_beheviour
WHERE
    discount_applied = 'yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer_beheviour);
            
#Q3. Which are the top 5 products with the highest average review rating?


select item_purchased,round(avg(review_rating),2) as "Average Product Rating" 
From customer_beheviour
Group by item_purchased
Order by avg(review_rating) desc limit 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

Select shipping_type, round(AVG(purchase_amount),2)  From customer_beheviour
Where shipping_type in ('Standard','Express')
group by shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenus between subscribers and non-subscribers.

Select subscription_status,
count(customer_id)as Total_customers,
round(avg(purchase_amount),2)as average_spend,
round(sum(purchase_amount),2) as tatal_revenu
From customer_beheviour
group by subscription_status
order by tatal_revenu,average_spend desc;


# 06. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
round(100* sum(case when discount_applied ='yes'then 1 else 0 END)/count(*),2) as discount_rate
From customer_beheviour
group by item_purchased
order by discount_rate desc limit 5;

#  Q7. Segment customers into New, Returning, and Loyal based on their total 
#      number of previous purchases, and show the count of each segment.

with customer_type as ( Select customer_id, previous_purchases,
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then'Returning'
Else 'Loyal'
END as customer_segment 
from customer_beheviour
)

Select customer_segment, count(*) as customer_count
from customer_type
group by customer_segment;

# Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_beheviour
    GROUP BY category, item_purchased
)

SELECT 
    item_rank, 
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank <= 3;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

Select subscription_status,
count(customer_id) as repeat_buyers
From customer_beheviour

where previous_purchases >5
group by subscription_status;

# Q10. What is the revenue contribution of each age group

Select age_group,
sum(purchase_amount) as total_revenue
From customer_beheviour
group by age_group
order by total_revenue desc;










